"""optimizer-bench case specifications (human-edited). tools/make_cases.py turns each spec into cases/<id>.json
(OptimizeRequest, docs/21 §2.1, with explicit candidate pools) and expected/<id>.json (exhaustive optimum).

Pool item syntax: "Module Name" or "Module Name|Charge Name". Every rack may also be left (partly) empty.
Constraint thresholds may be quantiles of the legal space, resolved once at generation time and written into the
case as concrete numbers: "q60" = 60th percentile of the metric over engine-valid fits (skills/CPU/PG/cal/slots ok).
skills: default_level for every skill not listed (all V = 5); levels: {skill name: level}.
"""
ALL5 = {"default_level": 5}

PROJ_AC = ["200mm AutoCannon I|EMP S", "200mm AutoCannon II|EMP S", "125mm Gatling AutoCannon II|EMP S",
           "280mm Howitzer Artillery I|EMP S"]
GYROS = ["Gyrostabilizer I", "Gyrostabilizer II", "Counterbalanced Compact Gyrostabilizer", "Republic Fleet Gyrostabilizer"]
SPEED_LOW = ["Overdrive Injector System I", "Overdrive Injector System II", "Nanofiber Internal Structure I",
             "Nanofiber Internal Structure II", "Inertial Stabilizers I"]
PROPS = ["1MN Afterburner I", "1MN Afterburner II", "5MN Microwarpdrive I", "5MN Microwarpdrive II",
         "1MN Monopropellant Enduring Afterburner"]
SPEED_RIGS = ["Small Auxiliary Thrusters I", "Small Polycarbon Engine Housing I"]

SPECS = [
    # ---------------------------------------------------------------- dps
    dict(id="dps_rifter_projectile", ship="Rifter", skills=ALL5, objective="dps",
         keep=[("1MN Afterburner I", "mid")],
         racks={"high": (3, PROJ_AC), "low": (4, GYROS + ["Overdrive Injector System I"]),
                "rig": (3, ["Small Projectile Burst Aerator I", "Small Projectile Collision Accelerator I"])},
         note="PG binds (280mm arty, 200mm II); calibration binds on 3 rigs"),
    dict(id="dps_rifter_projectile_meta4", ship="Rifter", skills=ALL5, objective="dps", meta=4,
         keep=[("1MN Afterburner I", "mid")],
         racks={"high": (3, PROJ_AC), "low": (4, GYROS + ["Overdrive Injector System I"]),
                "rig": (3, ["Small Projectile Burst Aerator I", "Small Projectile Collision Accelerator I"])},
         note="same space as dps_rifter_projectile, max_meta_level 4 excludes T2 (5) and faction (8)"),
    dict(id="dps_rifter_projectile_skills4", ship="Rifter", skills={"default_level": 4}, objective="dps",
         keep=[("1MN Afterburner I", "mid")],
         racks={"high": (3, PROJ_AC), "low": (4, GYROS + ["Overdrive Injector System I"]),
                "rig": (3, ["Small Projectile Burst Aerator I", "Small Projectile Collision Accelerator I"])},
         note="all skills IV: T2 guns need Small Projectile Turret V (MISSING_SKILL)"),
    dict(id="dps_merlin_hybrid_price", ship="Merlin", skills=ALL5, objective="dps", price="q40",
         keep=[("1MN Afterburner I", "mid")],
         racks={"high": (3, ["Light Neutron Blaster I|Antimatter Charge S", "Light Neutron Blaster II|Antimatter Charge S",
                             "Light Neutron Blaster II|Null S", "Light Ion Blaster I|Caldari Navy Antimatter Charge S"]),
                "low": (3, ["Magnetic Field Stabilizer I", "Magnetic Field Stabilizer II",
                            "Federation Navy Magnetic Field Stabilizer", "Power Diagnostic System I"]),
                "rig": (3, ["Small Hybrid Collision Accelerator I", "Small Hybrid Burst Aerator I"])},
         note="price ceiling (40th percentile of legal fits) binds"),
    dict(id="dps_kestrel_missile_cpu", ship="Kestrel", skills=ALL5, objective="dps",
         keep=[("Multispectrum Shield Hardener I", "mid"), ("Multispectrum Shield Hardener I", "mid")],
         racks={"high": (4, ["Light Missile Launcher I|Scourge Light Missile", "Light Missile Launcher II|Scourge Light Missile",
                             "Light Missile Launcher I|Caldari Navy Scourge Light Missile", "Light Missile Launcher II|Caldari Navy Scourge Light Missile"]),
                "low": (2, ["Ballistic Control System I", "Ballistic Control System II", "Co-Processor I"]),
                "rig": (3, ["Small Warhead Calefaction Catalyst I", "Small Bay Loading Accelerator I",
                            "Small Processor Overclocking Unit I"])},
         note="CPU binds (two kept shield hardeners + LML II / BCS II); Co-Processor and CPU rig trade against damage"),
    dict(id="dps_catalyst_blaster_pg", ship="Catalyst", skills=ALL5, objective="dps",
         keep=[("Medium Shield Extender I", "mid"), ("Medium Shield Extender I", "mid")],
         racks={"high": (6, ["Light Neutron Blaster I|Antimatter Charge S", "Light Ion Blaster I|Antimatter Charge S",
                             "Light Neutron Blaster II|Antimatter Charge S"]),
                "low": (3, ["Magnetic Field Stabilizer I", "Magnetic Field Stabilizer II", "Power Diagnostic System I",
                            "Reactor Control Unit I"]),
                "rig": (1, ["Small Ancillary Current Router I", "Small Hybrid Collision Accelerator I"])},
         note="PG binds (two kept Medium Shield Extenders + Neutron II); RCU / PDS / ACR trade against damage mods"),
    # ---------------------------------------------------------------- ehp
    dict(id="ehp_rifter_armor", ship="Rifter", skills=ALL5, objective="ehp",
         keep=[("1MN Afterburner I", "mid")],
         racks={"low": (4, ["200mm Steel Plates I", "200mm Steel Plates II", "400mm Steel Plates I",
                            "Multispectrum Energized Membrane I", "Multispectrum Energized Membrane II", "Damage Control II"]),
                "rig": (3, ["Small Trimark Armor Pump I", "Small Trimark Armor Pump II"])},
         note="PG binds (400mm plates); calibration binds (T2 rigs); maxGroupFitted (one Damage Control)"),
    dict(id="ehp_merlin_shield", ship="Merlin", skills=ALL5, objective="ehp",
         racks={"mid": (4, ["Medium Shield Extender I", "Medium Shield Extender II", "Small Shield Extender I",
                            "Multispectrum Shield Hardener I"]),
                "low": (3, ["Damage Control I", "Damage Control II", "Power Diagnostic System I", "Reactor Control Unit I"]),
                "rig": (3, ["Small Core Defense Field Extender I", "Small Core Defense Field Extender II"])},
         note="PG binds (medium extenders on a frigate)"),
    dict(id="ehp_punisher_armor_price", ship="Punisher", skills=ALL5, objective="ehp", price="q35",
         racks={"low": (5, ["200mm Steel Plates I", "200mm Steel Plates II", "Multispectrum Energized Membrane I",
                            "Multispectrum Energized Membrane II", "Damage Control II"]),
                "rig": (3, ["Small Trimark Armor Pump I", "Small Trimark Armor Pump II"])},
         note="price ceiling binds (T2 plates / membranes / rigs)"),
    dict(id="ehp_thorax_armor_meta1", ship="Thorax", skills=ALL5, objective="ehp", meta=1,
         racks={"low": (5, ["800mm Steel Plates I", "1600mm Steel Plates I", "Multispectrum Energized Membrane I",
                            "Multispectrum Energized Membrane II", "Damage Control I", "Damage Control II"]),
                "rig": (3, ["Medium Trimark Armor Pump I"])},
         note="cruiser; max_meta_level 1 removes T2; PG binds (1600mm plates)"),
    dict(id="ehp_rifter_armor_skills3", ship="Rifter", skills={"default_level": 3}, objective="ehp",
         keep=[("1MN Afterburner I", "mid")],
         racks={"low": (4, ["200mm Steel Plates I", "200mm Steel Plates II", "400mm Steel Plates I",
                            "Multispectrum Energized Membrane I", "Multispectrum Energized Membrane II", "Damage Control II"]),
                "rig": (3, ["Small Trimark Armor Pump I", "Small Trimark Armor Pump II"])},
         note="all skills III: T2 modules/rigs illegal (MISSING_SKILL), lower fitting skills tighten PG/CPU"),
    # ---------------------------------------------------------------- tank (sustained effective, EHP/s)
    dict(id="tank_incursus_armor_rep", ship="Incursus", skills=ALL5, objective="tank",
         racks={"mid": (3, ["Cap Recharger I", "Cap Recharger II", "1MN Afterburner I"]),
                "low": (4, ["Small Armor Repairer I", "Small Armor Repairer II", "Multispectrum Energized Membrane I",
                            "Multispectrum Energized Membrane II", "Damage Control II"]),
                "rig": (3, ["Small Auxiliary Nano Pump I", "Small Nanobot Accelerator I", "Small Capacitor Control Circuit I"])},
         note="cap-limited sustained armor tank; repairers vs membranes vs cap"),
    dict(id="tank_merlin_shield_boost", ship="Merlin", skills=ALL5, objective="tank",
         racks={"mid": (4, ["Small Shield Booster I", "Small Shield Booster II", "Medium Shield Booster I",
                            "Shield Boost Amplifier I", "Multispectrum Shield Hardener I", "Cap Recharger I"]),
                "low": (3, ["Damage Control II", "Power Diagnostic System I"]),
                "rig": (3, ["Small Core Defense Capacitor Safeguard I", "Small Capacitor Control Circuit I"])},
         note="PG binds (medium booster); cap-limited"),
    dict(id="tank_punisher_armor_meta0", ship="Punisher", skills=ALL5, objective="tank", meta=0,
         racks={"mid": (2, ["Cap Recharger I", "Cap Recharger II"]),
                "low": (5, ["Small Armor Repairer I", "Small Armor Repairer II", "Multispectrum Energized Membrane I",
                            "Damage Control I", "Capacitor Power Relay I"]),
                "rig": (3, ["Small Auxiliary Nano Pump I", "Small Nanobot Accelerator I"])},
         note="max_meta_level 0: only T1 meta-0 items"),
    dict(id="tank_tormentor_armor_skills", ship="Tormentor", objective="tank",
         skills={"default_level": 5, "levels": {"Repair Systems": 2, "Capacitor Management": 1, "Hull Upgrades": 2}},
         racks={"mid": (3, ["Cap Recharger I", "Cap Recharger II"]),
                "low": (4, ["Small Armor Repairer I", "Small Armor Repairer II", "Multispectrum Energized Membrane I",
                            "Multispectrum Energized Membrane II"]),
                "rig": (3, ["Small Auxiliary Nano Pump I", "Small Nanobot Accelerator I"])},
         note="custom skills: Repair Systems II, Hull Upgrades II (T2 rep / membrane illegal), Capacitor Management I"),
    # ---------------------------------------------------------------- speed
    dict(id="speed_slasher", ship="Slasher", skills=ALL5, objective="speed",
         racks={"mid": (2, PROPS), "low": (2, SPEED_LOW), "rig": (3, SPEED_RIGS)},
         note="maxGroupActive (one prop module active), PG binds (MWD II)"),
    dict(id="speed_rifter_price", ship="Rifter", skills=ALL5, objective="speed", price="q30",
         racks={"mid": (2, PROPS), "low": (4, SPEED_LOW), "rig": (3, SPEED_RIGS)},
         note="price ceiling binds"),
    dict(id="speed_atron_meta4", ship="Atron", skills=ALL5, objective="speed", meta=4,
         racks={"mid": (2, PROPS), "low": (3, SPEED_LOW), "rig": (3, SPEED_RIGS)},
         note="max_meta_level 4 removes T2 (meta 5); enduring AB (meta 1) allowed"),
    dict(id="speed_slasher_skills2", ship="Slasher", skills={"default_level": 2}, objective="speed",
         racks={"mid": (2, PROPS), "low": (2, SPEED_LOW), "rig": (3, SPEED_RIGS)},
         note="all skills II: MWD needs High Speed Maneuvering, T2 illegal; low fitting skills"),
    # ---------------------------------------------------------------- cap stable
    dict(id="cap_punisher_lasers", ship="Punisher", skills=ALL5, objective="cap_stable",
         keep=[("Small Focused Pulse Laser I", "high", "Multifrequency S")] * 3 + [("1MN Afterburner I", "mid")],
         racks={"mid": (1, ["Cap Recharger I", "Cap Recharger II"]),
                "low": (5, ["Capacitor Power Relay I", "Capacitor Power Relay II", "Power Diagnostic System I",
                            "Heat Sink I", "Capacitor Flux Coil I"]),
                "rig": (3, ["Small Capacitor Control Circuit I", "Small Semiconductor Memory Cell I"])},
         note="keep: 3 lasers + AB; maximise stable % (or time to empty)"),
    dict(id="cap_punisher_lasers_dps_floor", ship="Punisher", skills=ALL5, objective="cap_stable", min={"dps": "q50"},
         keep=[("Small Focused Pulse Laser I", "high", "Multifrequency S")] * 3 + [("1MN Afterburner I", "mid")],
         racks={"mid": (1, ["Cap Recharger I", "Cap Recharger II"]),
                "low": (5, ["Capacitor Power Relay I", "Capacitor Power Relay II", "Heat Sink I", "Heat Sink II",
                            "Capacitor Flux Coil I"]),
                "rig": (3, ["Small Capacitor Control Circuit I", "Small Energy Collision Accelerator I"])},
         note="attribute floor: dps >= median forces heat sinks against cap mods"),
    dict(id="cap_incursus_reps_price", ship="Incursus", skills=ALL5, objective="cap_stable", price="q50",
         keep=[("Small Armor Repairer I", "low"), ("Small Armor Repairer I", "low"), ("1MN Afterburner I", "mid")],
         racks={"mid": (2, ["Cap Recharger I", "Cap Recharger II"]),
                "low": (2, ["Capacitor Power Relay I", "Capacitor Power Relay II", "Capacitor Flux Coil I"]),
                "rig": (3, ["Small Capacitor Control Circuit I", "Small Semiconductor Memory Cell I"])},
         note="keep: dual rep + AB; price ceiling"),
    dict(id="cap_tormentor_meta0_skills", ship="Tormentor", objective="cap_stable", meta=0,
         skills={"default_level": 5, "levels": {"Capacitor Management": 2, "Capacitor Systems Operation": 2}},
         keep=[("Small Focused Pulse Laser I", "high", "Multifrequency S")] * 3,
         racks={"mid": (3, ["Cap Recharger I", "Cap Recharger II", "1MN Afterburner I"]),
                "low": (4, ["Capacitor Power Relay I", "Capacitor Power Relay II", "Capacitor Flux Coil I", "Heat Sink I"]),
                "rig": (3, ["Small Capacitor Control Circuit I"])},
         note="max_meta_level 0 + weak cap skills"),
    # ---------------------------------------------------------------- price (minimise)
    dict(id="price_rifter_dps_floor", ship="Rifter", skills=ALL5, objective="price", min={"dps": "q75"},
         keep=[("1MN Afterburner I", "mid")],
         racks={"high": (3, PROJ_AC), "low": (4, GYROS), "rig": (3, ["Small Projectile Burst Aerator I"])},
         note="cheapest fit with dps >= 75th percentile"),
    dict(id="price_merlin_ehp_floor", ship="Merlin", skills=ALL5, objective="price", min={"ehp": "q70"},
         racks={"mid": (4, ["Medium Shield Extender I", "Medium Shield Extender II", "Small Shield Extender I",
                            "Multispectrum Shield Hardener I"]),
                "low": (3, ["Damage Control I", "Damage Control II", "Power Diagnostic System I"]),
                "rig": (3, ["Small Core Defense Field Extender I", "Small Core Defense Field Extender II"])},
         note="cheapest fit with ehp >= 70th percentile"),
    dict(id="price_slasher_speed_floor", ship="Slasher", skills=ALL5, objective="price", min={"speed": "q80"},
         racks={"mid": (2, PROPS), "low": (2, SPEED_LOW), "rig": (3, SPEED_RIGS)},
         note="cheapest fit with speed >= 80th percentile"),
    dict(id="price_incursus_cap_stable_tank", ship="Incursus", skills=ALL5, objective="price", cap_stable=True,
         min={"tank": "q60"},
         racks={"mid": (3, ["Cap Recharger I", "Cap Recharger II", "1MN Afterburner I"]),
                "low": (4, ["Small Armor Repairer I", "Small Armor Repairer II", "Multispectrum Energized Membrane I",
                            "Capacitor Power Relay I"]),
                "rig": (3, ["Small Auxiliary Nano Pump I", "Small Capacitor Control Circuit I"])},
         note="cheapest cap-stable fit with tank >= 60th percentile"),
]
