#!/usr/bin/env python3
"""Write optimizer/prices.json: a FIXED, SYNTHETIC price table (ISK) for every type the specs use. Not market data;
it only has to be pinned and plausible (T1 < compact < T2 < faction, bigger modules cost more) so price ceilings and
price minimisation are reproducible. Re-running this script must not change existing prices (new types are added)."""
import json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import lib, specs  # noqa: E402

SHIP = {25: 350_000, 420: 1_100_000, 26: 9_000_000, 324: 25_000_000}
META_MULT = {2: 12.0, 3: 20.0, 4: 60.0, 5: 400.0, 6: 150.0}


def size_mult(name):
    for keys, m in ((("1600mm", "Large ", "50MN", "Heavy "), 12.0), (("800mm", "Medium ", "10MN"), 4.0),
                    (("400mm", "5MN"), 2.0)):
        if any(k in name for k in keys):
            return m
    return 1.0


def price(tid):
    t = lib.tinfo(tid)
    name, cat, mg, ml = t["name"], t["category"], t.get("meta_group") or 1, lib.meta_level(tid)
    if cat == 6:
        return SHIP[t["group"]]
    if cat == 8:   # one load of charges
        return {1: 1_500, 2: 30_000, 4: 12_000}.get(mg, 5_000)
    is_rig = lib.tattr(tid, "rigSize") is not None and lib.tattr(tid, "upgradeCost") is not None
    base = (350_000 if "Small " in name else 1_400_000) if is_rig else 25_000 * size_mult(name)
    if mg == 1:
        return round(base * (1.0 if ml == 0 else 1.5 + 0.5 * ml))
    return round(base * META_MULT.get(mg, 10.0))


def main():
    p = Path(lib.ROOT / "prices.json")
    old = json.loads(p.read_text())["prices"] if p.exists() else {}
    names = set()
    for s in specs.SPECS:
        names.add(s["ship"])
        for k in s.get("keep", []):
            names.add(k[0]); names.update(k[2:3])
        for _, (_, pool) in s["racks"].items():
            for it in pool:
                names.update(it.split("|"))
    out = dict(old)
    for n in sorted(names):
        tid = lib.by_name()[n]
        out.setdefault(str(tid), {"name": n, "isk": price(tid)})
    p.write_text(json.dumps({"description": "optimizer-bench pinned synthetic price table (ISK per item; charges per load). "
                             "Not market data. Generated by tools/make_prices.py; existing entries never change.",
                             "prices": dict(sorted(out.items(), key=lambda kv: int(kv[0])))}, indent=1, ensure_ascii=False) + "\n")
    print(len(out), "prices")


if __name__ == "__main__":
    main()
